name: Release
on:
  release:
    types: [published]
jobs:
  release:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      - name: Set up dotnet.
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
      - name: Build
        run: dotnet build --configuration Release Lib.Health.csproj -p:Version=${{ github.event.release.tag_name }}
      - name: Package
        run: dotnet pack --configuration Release Lib.Health.csproj -p:Version=${{ github.event.release.tag_name }}
      - name: publish GH
        run: dotnet nuget push bin/Release/*.nupkg -k ${{secrets.GITHUB_TOKEN}} -s https://nuget.pkg.github.com/jitesoft/index.json
